---
layout: cv
title: "Jacob Holst"
---
Software Engineer, Full-Stack Developer, Data Scientist

<div id="webaddress">
<a href="https://automatic-meme-4gwl794.pages.github.io/resume.html">My Website</a>
</div>


### Specialized in

Python, C#/C++, JavaScript


### Research interests

Graphic User Interfaces, AI Models, Data Organization


## Education

`2022-2025`
__BYU-Idaho__

Bachelor's of Computer Science, with a Minor in Mathematics and emphasis on Machine Learning
- 3.83 GPA

## Occupation

`April-July 2025`
__Software Developer Intern__, Case Tech, LLc

- Customized several EC2 instances to the needs of a project: implemented network traffic rules, set private keys, 
used SSH to access servers, and used different CPU types to host them 
- Used Wordpress to create a front-end interface for a company website, with Docker, MySQL, and Bash used to 
build the work environment; utilized wireframes in development 
- Created a job board React app designed similar the interface of indeed.com, with implemented OAuth and 
connection to a MySQL database through JS Node

`2022-2026`
__Shift Lead__, Walgreens Co.

- Resolved connection issues, printer jams, and other computer-related problems that coworkers could not resolve 
themselves, saving time and money that would go into fix-it tickets 
- Used algorithmic thinking to make inventory counts up to 20% more accurate 
- Reduced time spent both stocking and resetting shelves by up to 30% with principles of time complexity 
- Trained several coworkers on procedures relating to money handling, step-by-step assembly of products in the 
photo lab, and making reports of daily compliance with company policy 
- Exercised reasoning skills and best judgment in finding creative solutions to a variety of problems, including 
finding lost photo orders, resolving computer errors with reading coupons, and fixing mismatching price labels

`2019`
__Data Entry__, North Park Transportation

- Transferred data from shipping bills to a digital format with speed and accuracy
- Learned area information to optimize routing and package preparation, becoming familiar with proceedures for handling hazardous materials

<!-- ### Footer

Last updated: November 2025 -->